### ISSUE TITLE
log transceive request properly upon error

### ISSUE THREAD

**Issue by sant0s** [nfcim/flutter_nfc_kit#102]
upon a transceive error, the following is logged:

```
E/im.nfc.flutter_nfc_kit.FlutterNfcKitPlugin( 5290): Transceive Error: [B@95d3c9e
E/im.nfc.flutter_nfc_kit.FlutterNfcKitPlugin( 5290): android.nfc.TagLostException: Tag was lost.
E/im.nfc.flutter_nfc_kit.FlutterNfcKitPlugin( 5290): 	at android.nfc.TransceiveResult.getResponseOrThrow(TransceiveResult.java:48)
E/im.nfc.flutter_nfc_kit.FlutterNfcKitPlugin( 5290): 	at android.nfc.tech.BasicTagTechnology.transceive(BasicTagTechnology.java:151)
E/im.nfc.flutter_nfc_kit.FlutterNfcKitPlugin( 5290): 	at android.nfc.tech.NfcA.transceive(NfcA.java:137)
E/im.nfc.flutter_nfc_kit.FlutterNfcKitPlugin( 5290): 	at java.lang.reflect.Method.invoke(Native Method)
```

it'd be nice if the request after "Transceive Error: " could be logged properly.

**Comment by Harry-Chen** [comment]
Thanks for you advice.
