### ISSUE TITLE
Crash when scanning nfc

### ISSUE THREAD

**Issue by martijn00** [nfcim/flutter_nfc_kit#128]
Since the last release I get this error:

type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast

```
#0      _$NFCTagFromJson (package:flutter_nfc_kit/flutter_nfc_kit.g.dart:47:52)
#1      new NFCTag.fromJson (package:flutter_nfc_kit/flutter_nfc_kit.dart:145:57)
#2      FlutterNfcKit.poll (package:flutter_nfc_kit/flutter_nfc_kit.dart:344:19)
<asynchronous suspension>
#3      NfcCubit.startScanning (package:spotted_ui/src/features/my_pets/cubit/nfc_cubit.dart:47:7)
<asynchronous suspension>

```

My nfc tag is ultralight and i just contains a string with a url.

```
await FlutterNfcKit.poll(iosAlertMessage: iosPollText);
      await FlutterNfcKit.setIosAlertMessage(iosScanInProgressText);
      await FlutterNfcKit.readNDEFRecords(cached: false).then(
        (value) => guid = _getGuidFromRecords(value),
      );

String? _getGuidFromRecords(List<NDEFRecord> records) {
    String? guid;
    for (final record in records) {
      if (record is UriRecord) {
        guid = AppHelpers.getTagGuid(record.uri?.toString());
      }
    }
    return guid;
  }
```

**Comment by Harry-Chen** [comment]
Duplicated with #126
