### ISSUE TITLE
NFC service not responding after failed to recover - Android

### ISSUE THREAD

**Issue by haizadvnet** [nfcim/flutter_nfc_kit#149]
This issue rarely happened and I don't know why. I assumed it because that I scan the NFC tag multiple times. Can we handle the exception error on plugin level?

Android version 8
flutter_nfc_kit 3.3.3

Reference

1. [What are the possible reasons for NFC Service to become dead after some time?](https://stackoverflow.com/questions/55621854/what-are-the-possible-reasons-for-nfc-service-to-become-dead-after-some-time)

2. https://stackoverflow.com/a/32263441/7228432 `I have come across the same issue and was able to resolve. This happens when you try to invoke NFC beam, when Activity is not in Resumed State.`- [BlackPearl](https://stackoverflow.com/users/2597738/blackpearl)

Error log
```
E/NFC     (10828): NFC service dead - attempting to recover
E/NFC     (10828): android.os.DeadObjectException
E/NFC     (10828): 	at android.os.BinderProxy.transactNative(Native Method)
E/NFC     (10828): 	at android.os.BinderProxy.transact(Binder.java:748)
E/NFC     (10828): 	at android.nfc.INfcAdapter$Stub$Proxy.getState(INfcAdapter.java:409)
E/NFC     (10828): 	at android.nfc.NfcAdapter.isEnabled(NfcAdapter.java:712)
E/NFC     (10828): 	at im.nfc.flutter_nfc_kit.FlutterNfcKitPlugin.handleMethodCall(FlutterNfcKitPlugin.kt:71)
E/NFC     (10828): 	at im.nfc.flutter_nfc_kit.FlutterNfcKitPlugin.onMethodCall(FlutterNfcKitPlugin.kt:59)
E/NFC     (10828): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/NFC     (10828): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/NFC     (10828): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/NFC     (10828): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/NFC     (10828): 	at android.os.Handler.handleCallback(Handler.java:869)
E/NFC     (10828): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/NFC     (10828): 	at android.os.Looper.loop(Looper.java:206)
E/NFC     (10828): 	at android.app.ActivityThread.main(ActivityThread.java:6733)
E/NFC     (10828): 	at java.lang.reflect.Method.invoke(Native Method)
E/NFC     (10828): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/NFC     (10828): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
E/NFC     (10828): could not retrieve NFC service during service recovery
E/NFC     (10828): NFC service dead - attempting to recover
E/NFC     (10828): android.os.DeadObjectException
E/NFC     (10828): 	at android.os.BinderProxy.transactNative(Native Method)
E/NFC     (10828): 	at android.os.BinderProxy.transact(Binder.java:748)
E/NFC     (10828): 	at android.nfc.INfcAdapter$Stub$Proxy.setReaderMode(INfcAdapter.java:664)
E/NFC     (10828): 	at android.nfc.NfcActivityManager.setReaderMode(NfcActivityManager.java:241)
E/NFC     (10828): 	at android.nfc.NfcActivityManager.disableReaderMode(NfcActivityManager.java:233)
E/NFC     (10828): 	at android.nfc.NfcAdapter.disableReaderMode(NfcAdapter.java:1442)
E/NFC     (10828): 	at im.nfc.flutter_nfc_kit.FlutterNfcKitPlugin$handleMethodCall$2.invoke(FlutterNfcKitPlugin.kt:134)
E/NFC     (10828): 	at im.nfc.flutter_nfc_kit.FlutterNfcKitPlugin$handleMethodCall$2.invoke(FlutterNfcKitPlugin.kt:118)
E/NFC     (10828): 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
E/NFC     (10828): NFC service dead - attempting to recover
E/NFC     (10828): android.os.DeadObjectException
```

**Comment by Harry-Chen** [comment]
Fixed in #149.
