### ISSUE TITLE
Reading AbsoluteURI record throws exception

### ISSUE THREAD

**Issue by timnew** [nfcim/flutter_nfc_kit#66]
I got an error when reading `AbsoluteURIRecord`

```
flutter: Invalid argument(s): AbsoluteURI record has no payload, don't set it
flutter:
#0      AbsoluteUriRecord.payload=
package:ndef/record/absoluteUri.dart:43
#1      NDEFRecord.doDecode
package:ndef/record.dart:275
#2      decodePartialNdefMessage
package:ndef/ndef.dart:42
#3      NDEFRecordConvert.fromRaw
package:flutter_nfc_kit/flutter_nfc_kit.dart:147
#4      FlutterNfcKit.readNDEFRecords.<anonymous closure>
package:flutter_nfc_kit/flutter_nfc_kit.dart:241
#5      MappedListIterable.elementAt (dart:_internal[/iterable.dart:413:31]())
#6      ListIterator.moveNext (dart:_internal[/iterable.dart:342:26]())
#7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch[/growable_array.dart:188:27]())
#8      new _GrowableList.of (dart:core-patch[/growable_array.dart:150:28]())
#9      new List.of (dart:core-patch[/array_patch.dart:51:28]())
#10     ListIterable.toList (dart:_internal[/iterable.dart:213:44]())
#11     FlutterNfcKit.readNDEFRecords
package:flutter_nfc_kit/flutter_nfc_kit.dart:242
<asynchronous suspension>
...
```

The issue is because `NDEFRecord.doDecode` set the payload after creating the record instance.

```dart
  static NDEFRecord doDecode(
      TypeNameFormat tnf, Uint8List type, Uint8List payload,
      {Uint8List? id,
      TypeFactory typeFactory = NDEFRecord.defaultTypeFactory}) {
    var record = typeFactory(tnf, utf8.decode(type));
    if (payload.length < record.minPayloadLength) {
      throw ArgumentError(
          "Payload length must be >= ${record.minPayloadLength}");
    }
    if (record.maxPayloadLength != null &&
        payload.length < record.maxPayloadLength!) {
      throw ArgumentError(
          "Payload length must be <= ${record.maxPayloadLength}");
    }
    record.id = id;
    record.type = type;
    // use setter for implicit decoding
    record.payload = payload;
    return record;
  }
```

And `AbsoluteUriRecord` has the following implementation:
```dart
//absoluteURI record has no payload
  Uint8List? get payload {
    return null;
  }

  set payload(Uint8List? payload) {
    throw ArgumentError("AbsoluteURI record has no payload, don't set it");
  }
```

I'm not sure how to fix the issue, as it either breaks the AbsoluteUri definition or there is some heavy rewriting needed on the NDEF decoding side.

**Comment by timnew** [comment]
Issue occurs in ndef package. And need to be patched there.
